version: "3.8"

services:
  dev-db:
    image: postgres:13
    ports:
      -  "30001:30001"  # PostgreSQL default port is 5432, not 3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest